### ISSUE TITLE
benchmark.py 运行问题

### ISSUE THREAD

**Issue by Magic-Pony** [GuoPingPan/Habitat-Sim-Usage-Chinese#3]
我按照原项目的readme指示，执行examples/benchmark.py --scene /path/to/mp3d_example/17DRP5sb8fy/17DRP5sb8fy.glb：
`python /home/lcy-magic/VLN_TEST/habitat-sim/examples/benchmark.py --scene /home/lcy-magic/VLN_TEST/habitat-sim/data/mp3d_example/17DRP5sb8fy/17DRP5sb8fy.glb`
遇到如下问题：
`/home/lcy-magic/VLN_TEST/habitat-sim/data/mp3d_example/17DRP5sb8fy/17DRP5sb8fy.glb
 ---------------------- rgb ------------------------ 
Traceback (most recent call last):
  File "/home/lcy-magic/VLN_TEST/habitat-sim/examples/benchmark.py", line 120, in <module>
    perf[key] = demo_runner.benchmark(settings)
  File "/home/lcy-magic/VLN_TEST/habitat-sim/examples/demo_runner.py", line 395, in benchmark
    perfs = pool.map(self._bench_target, range(nprocs))
  File "/home/lcy-magic/anaconda3/envs/ONE4ALL/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/lcy-magic/anaconda3/envs/ONE4ALL/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/home/lcy-magic/anaconda3/envs/ONE4ALL/lib/python3.10/multiprocessing/pool.py", line 540, in _handle_tasks
    put(task)
  File "/home/lcy-magic/anaconda3/envs/ONE4ALL/lib/python3.10/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/lcy-magic/anaconda3/envs/ONE4ALL/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: cannot pickle '_magnum.Color4' object`
而运行：
`python /home/lcy-magic/VLN_TEST/habitat-sim/examples/example.py --scene /home/lcy-magic/VLN_TEST/habitat-sim/data/mp3d_example/17DRP5sb8fy/17DRP5sb8fy.glb --enable_physics`
就没问题。请问有什么解决思路吗？谢谢。

**Comment by GuoPingPan** [comment]
很久没碰habitat了，如果我找到解决方法之后在这里回复你，另外直接在habitat提issue也是一个很好的解决方案哦~
（我之前许多问题都得到了他们的帮助）

**Comment by BIT-TYJ** [comment]
请问habitat中能够改变物体的位置或者增加物体吗
